name: mega_flutter_network
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^2.0.1
  dio: ^3.0.10
  flutter_modular: ^2.0.1
  flutter_user_agent: ^1.2.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  json_annotation: ^3.1.0
  mime: ^0.9.7
  package_info: ^0.4.3+2
  path_provider: ^1.6.24

  mega_flutter_base:
    path: ../mega_flutter_base

  megaleios_flutter_localization:
    path: ../megaleios_flutter_localization

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  hive_generator: ^0.8.2
  json_serializable: ^3.5.0

flutter: