name: mega_flutter_base
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_pattern: ^2.5.1
  cpfcnpj: ^1.0.3
  email_validator: ^1.0.6
  strings: ^0.1.4
  connectivity: ^2.0.1
  flutter_masked_text: ^0.8.0
  flutter_modular: ^2.0.1
  font_awesome_flutter: ^8.10.0
  intl: ^0.16.1
  mask_text_input_formatter: ^1.1.0
  modal_progress_hud: ^0.1.3
  rxdart: ^0.24.1

  mega_flutter_components:
    path: ../mega_flutter_components

  mega_flutter_network:
    path: ../mega_flutter_network

  megaleios_flutter_localization:
    path: ../megaleios_flutter_localization

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
